### ISSUE TITLE
책장에 담지 않은 도서에 코멘트를 남길 경우 에러 메세 미노출

### ISSUE THREAD

**Issue by youngjijang** [prgrms-web-devcourse/Team-Gaerval-Dadok-FE#285]
# 버그설명
책장에 담지 않은 도서에 코멘트를 남길 경우 에러 메세 미노출

# 원하는 결과
에러 메세지 혹은 책장 담기 권유 메세지가 노출되어야합니다.

**Comment by minjongbaek** [comment]
@gxxrxn 규란님이 책 코멘트를 담당해서 일단 Assignees에 규란님을 등록해두었습니다.
만약 다른 분들이 보시고 비교적 적은 리소스로 해결이 가능하다면 대신 작업을 해도 좋을 것 같아요!
