### ISSUE TITLE
가입 날짜가 지난 모임 참여 신청시 잘못된 에러 메세지 노출

### ISSUE THREAD

**Issue by youngjijang** [prgrms-web-devcourse/Team-Gaerval-Dadok-FE#286]
# 버그설명
가입 날짜가 지난 모임 참여 신청시 잘못된 에러 메세지 노출

# 원하는 결과
모임참여 버튼이 딤드되어 버튼을 못 누르게 하면 좋을 것 같아요!

# 실제 결과
모임 참여하기 버튼 클릭시 비밀번호가 맞지 않다는 에러 메세지 노출

# 스크린샷
https://dev.dadok.site/group/89
해당 모임입니다~

**Comment by minjongbaek** [comment]
@WooDaeHyun 대현님이 모임 참여 기능을 담당해서 일단 Assignees에 대현님을 등록해두었습니다.
만약 다른 분들이 보시고 비교적 적은 리소스로 해결이 가능하다면 대신 작업을 해도 좋을 것 같아요!

**Comment by WooDaeHyun** [comment]
확인했습니다! 해당 부분 확인하고 수정하도록 하겠습니다!~ 확인 감사합니다!
