### ISSUE TITLE
도서 검색 -> 상세 페이지 -> 이전 페이지 -> 검색창이 유지되면 좋을 것 같아요.

### ISSUE THREAD

**Issue by youngjijang** [prgrms-web-devcourse/Team-Gaerval-Dadok-FE#287]
# 버그설명
도서 검색 -> 상세 페이지 -> 이전 페이지 -> 검색창이 유지되면 좋을 것 같아요.

# 원하는 결과
뒤로가기 시에 이전 검색 페이지가 유지되면 좋을 것 같아요.

# 실제 결과
검색결과가 초기화 됩니다.

# 스크린샷

**Comment by hanyugeon** [comment]
#593 해당 이슈를 통해 기능이 구현되어 이슈 닫도록 하겠습니다!
